// Topic: Eat
const eatTags = [
    'restaurant',
    'fast_food',
    'pub',
    'cafe',
    'bar',
    'ice_cream',
    'bbq',
    'bakery',
    'pastry',
    'deli',
    'coffee',
    'tea',
    'wine',
    'alcohol',
    'rice',
    'seafood',
    'butcher',
    'greengrocer',
    'cheese',
    'fishmonger',
    'tofu',
    'pizza',
    'noodle',
    'frozen_food',
    'health_food',
    'spices',
    'dairy',
    'tofu_shop',
    'dried_fish',
    'chocolate',
    'drink_stand'
];

// Topic: Live
const liveTags = [
    'hotel',
    'guest_house',
    'hostel',
    'camp_site',
    'camp_pitch',
    'motel',
    'apartment',
    'chalet',
    'love_hotel',
    'caravan_site',
    'alpine_hut',
    'wilderness_hut'
];

// Topic: Shop
const shopTags = [
    'convenience',
    'supermarket',
    'clothes',
    'car',
    'confectionery',
    'variety_store',
    'mobile_phone',
    'books',
    'bicycle',
    'florist',
    'electronics',
    'shoes',
    'motorcycle',
    'gift',
    'second_hand',
    'stationery',
    'sports',
    'doityourself',
    'car_parts',
    'jewelry',
    'pet',
    'furniture',
    'toys',
    'tobacco',
    'hardware',
    'farm',
    'video',
    'houseware',
    'lottery',
    'musical_instrument',
    'hobby',
    'bag',
    'cosmetics',
    'newsagent',
    'department_store',
    'general',
    'music',
    'tyres',
    'computer',
    'outdoor',
    'bed',
    'interior_decoration',
    'beverages',
    'art',
    'baby_goods',
    'mall',
    'kiosk',
    'garden_centre',
    'antiques',
    'fishing',
    'watches',
    'wholesale',
    'fabric',
    'food',
    'trade',
    'boutique',
    'appliance',
    'electrical',
    'sewing',
    'fashion_accessories',
    'camera',
    'craft',
    'video_games',
    'model',
    'paint',
    'pottery',
    'curtain',
    'collector',
    'scuba_diving',
    'carpet',
    'hifi',
    'radiotechnics',
    'games',
    'agrarian',
    'grocery',
    'frame',
    'household',
    'leather',
    'wigs',
    'herbalist',
    'accessories',
    'balloon',
    'surf',
    'umbrella',
    'dry_food',
    'shopping_centre',
    'ice',
    'weapons',
    'party',
    'lighting',
    'doll',
    'doors',
    'electric',
    'market',
    'glassware',
    'wrapping',
    'paper',
    'electronic_parts',
    'glass',
    'office_supplies',
    'wedding',
    'seal',
    'haberdashery',
    'catalogue',
    'oil',
    'candles',
    'machinery',
    'honey',
    'recycle_shop',
    'handicrafts',
    'specialty',
    'signs',
    'aroma',
    'flag',
    'agricultural_engines',
    'mount',
    'china',
    'tennis',
    'antiques;art',
    'e-cigarette',
    'milk',
    'masking_tape',
    'bathroom_furnishing',
    'laboratory_equipment',
    'magic_and_illusion_supplies',
    'design_lights',
    'exterior',
    'design',
    'tiles',
    'pyrotechnics',
    'hunting',
    'fresh_fish,_processed_fish,_soy_products',
    'bridal_ring',
    'golf_cart',
    'commercial_product',
    'welfare_goods',
    'souvenir',
    'retail'
];

// Topic: Entertainment
const entertainmentTags = [
    'theatre',
    'cinema',
    'nightclub',
    'arts_centre',
    'casino',
    'gambling',
    'swimming_pool',
    'bowling_alley',
    'karaoke',
    'amusement_arcade',
    'adult_gaming_centre',
    'dance',
    'fitness_centre',
    'fitness_station',
    'sports_centre',
    'stadium',
    'pitch',
    'sports_hall',
    'park',
    'playground',
    'zoo',
    'aquarium',
    'theme_park',
    'museum',
    'gallery',
    'attraction',
    'viewpoint',
    'mahjong',
    'pachinko',
    'fortune_teller',
    'video_arcade',
    'water_park',
    'go',
    'darts',
    'board_game',
    'board_games',
    'escape_game',
    'art_school',
    'nature_reserve',
    'hot_spring',
    'bird_hide',
    'swimming_area',
    'beach_resort',
    'horse_riding',
    'bookmaker',
    'surf',
    'golf',
    'erotic',
    'psychic',
    'anime'
];

// Topic: Utility
const utilityTags = [
    'pharmacy',
    'vending_machine',
    'toilets',
    'drinking_water',
    'waste_basket',
    'atm',
    'bank',
    'fuel',
    'car_rental',
    'boat_rental',
    'charging_station',
    'smoking_area',
    'public_bath',
    'internet_cafe',
    'information',
    'storage_rental',
    'laundry',
    'optician',
    'car_repair',
    'funeral_directors',
    'chemist',
    'money_lender',
    'repair',
    'locksmith',
    'motorcycle_repair',
    'delivery',
    'telecommunication',
    'token_buyer',
    'logistics',
    'travel_agency',
    'print',
    'copyshop',
    'hairdresser',
    'massage',
    'dry_cleaning',
    'beauty',
    'pet_grooming',
    'tattoo',
    'photo_studio',
    'hearing_aids',
    'medical_supply',
    'salon',
    'security',
    'gas',
    'towing',
    'tool_hire',
    'printing',
    'eyelash_salon',
    'health',
    'gas_facilities',
    'sheet_metal_contactor',
    'groundskeeping',
    'key',
    'insurance',
    'service'
];

// // Topic: Other
// const otherTags = [
//     'school',
//     'university',
//     'college',
//     'library',
//     'research_institute',
//     'social_facility',
//     'social_centre',
//     'prison',
//     'religion',
//     'charity',
//     'no',
//     'Konyaku Donya',
//     'gus',
//     'militally',
//     'propangus',
//     '在宅介護ステーション',
//     '東京システム運輸',
//     '三井造船マシナリーサービス',
//     'リフレッシュサロン',
//     '吉田クリニック',
//     '不動産'
// ];

// Update the exports at the bottom of the file
export {
  eatTags,
  liveTags,
  shopTags,
  entertainmentTags,
  utilityTags
};
